# Generated by Django 5.2.6 on 2025-10-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
