# Generated by Django 5.2.6 on 2025-10-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
